<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/modules.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['surveys'] = "Questionnaires";
$GLOBALS['TL_LANG']['MOD']['survey']['0'] = "Questionnaires";
$GLOBALS['TL_LANG']['MOD']['survey']['1'] = "Créer des questionnaires en ligne.";
$GLOBALS['TL_LANG']['MOD']['scale']['0'] = "Jeux d'étiquettes";
$GLOBALS['TL_LANG']['MOD']['scale']['1'] = "Créer des jeux d'étiquettes ordonnées pour les questions.";
 
?>
