<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_survey']['title']['1'] = "Saisir le titre du questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['author']['0'] = "Auteur";
$GLOBALS['TL_LANG']['tl_survey']['author']['1'] = "Saisir le nom de l'auteur.";
$GLOBALS['TL_LANG']['tl_survey']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_survey']['description']['1'] = "Saisir une description pour le questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['tstamp']['0'] = "Dernière modification";
$GLOBALS['TL_LANG']['tl_survey']['tstamp']['1'] = "Date et heure des dernières modifications.";
$GLOBALS['TL_LANG']['tl_survey']['language']['0'] = "Langue";
$GLOBALS['TL_LANG']['tl_survey']['language']['1'] = "Choisir une langue pour le questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['introduction']['0'] = "Introduction";
$GLOBALS['TL_LANG']['tl_survey']['introduction']['1'] = "Saisir une introduction pour le questionnaire. L' introduction est affichée sur la page de départ du questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['finalsubmission']['0'] = "Dernière déclaration";
$GLOBALS['TL_LANG']['tl_survey']['finalsubmission']['1'] = "Saisir une dernière déclaration . La dernière déclaration est montrée quand le questionnaire est fini.";
$GLOBALS['TL_LANG']['tl_survey']['online_start']['0'] = "Afficher à partir du";
$GLOBALS['TL_LANG']['tl_survey']['online_start']['1'] = "Ne pas afficher le questionnaire sur le site avant ce jour.";
$GLOBALS['TL_LANG']['tl_survey']['online_end']['0'] = "Afficher jusqu'au";
$GLOBALS['TL_LANG']['tl_survey']['online_end']['1'] = "Ne pas afficher la page sur le site après ce jour.";
$GLOBALS['TL_LANG']['tl_survey']['limit_groups']['0'] = "Limité aux membres";
$GLOBALS['TL_LANG']['tl_survey']['limit_groups']['1'] = "Accès limité aux groupes de membres sélectionnées.";
$GLOBALS['TL_LANG']['tl_survey']['allowed_groups']['0'] = "Groupes de membres";
$GLOBALS['TL_LANG']['tl_survey']['allowed_groups']['1'] = "Choisir les groupes de membres qui peuvent participer à ce questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['access']['0'] = "Accès au questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['access']['1'] = "Choisir la méthode appropriée pour l'accès à ce questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['access']['explanation'] = "Choisir la méthode appropriée pour l'accès à ce questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['access']['anon']['0'] = "Accès anonyme";
$GLOBALS['TL_LANG']['tl_survey']['access']['anon']['1'] = "Tout le monde peut participer au questionnaire, même plusieurs fois. L'accès est anonyme. Les résultats du questionnaire ne sont pas suivis pour un participant.";
$GLOBALS['TL_LANG']['tl_survey']['access']['anoncode']['0'] = "Accès anonyme avec code TAN";
$GLOBALS['TL_LANG']['tl_survey']['access']['anoncode']['1'] = "Seuls les participants ayant un code TAN valide peuvent participer au questionnaire. Un questionnaire peut être fini qu'une seule fois par code TAN. L'accès est anonyme. Les résultat du questionnaire sont suivis pour chaque code TAN.";
$GLOBALS['TL_LANG']['tl_survey']['access']['nonanoncode']['0'] = "Accès personnalisé";
$GLOBALS['TL_LANG']['tl_survey']['access']['nonanoncode']['1'] = "Seuls les participants ayant pouvant ce connecter participeront au questionnaire. Un questionnaire peut être fini qu'une seule fois par participant. Les résultats du questionnaire sont suivis pour chaque participant.";
$GLOBALS['TL_LANG']['tl_survey']['usecookie']['0'] = "Se souvenir des participants";
$GLOBALS['TL_LANG']['tl_survey']['usecookie']['1'] = "Se souvenir des participants au questionnaire avec un cookie.";
$GLOBALS['TL_LANG']['tl_survey']['show_title']['0'] = "Afficher le titre du questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['show_title']['1'] = "Toujours afficher le titre du questionnaire en haut du questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['show_cancel']['0'] = "Afficher la commande d'annulation";
$GLOBALS['TL_LANG']['tl_survey']['show_cancel']['1'] = "Toujours afficher une commande <strong>Quitter ce questionnaire</strong> en haut du questionnaire.";
$GLOBALS['TL_LANG']['tl_survey']['allowback']['0'] = "Afficher le bouton \"Précédent\"";
$GLOBALS['TL_LANG']['tl_survey']['allowback']['1'] = "Afficher un bouton \"Précédent\" dans la navigation du questionnaire pour revenir à la page précédente.";
$GLOBALS['TL_LANG']['tl_survey']['jumpto']['0'] = "Rediriger vers une page";
$GLOBALS['TL_LANG']['tl_survey']['jumpto']['1'] = "Sélectionner une page de redirection quand le questionnaire est fini.";
$GLOBALS['TL_LANG']['tl_survey']['new']['0'] = "Nouveau questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['new']['1'] = "Créer un nouveau questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['show']['0'] = "Détails du questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['show']['1'] = "Afficher les détails du questionnaire %s";
$GLOBALS['TL_LANG']['tl_survey']['edit']['0'] = "Éditer le questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['edit']['1'] = "Éditer le questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey']['edit_']['0'] = "Vous ne pouvez pas éditer le questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['edit_']['1'] = "Le questionnaire ID %s est verrouillé. Des résultats de participants existent déjà.";
$GLOBALS['TL_LANG']['tl_survey']['participants']['0'] = "Participants au questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['participants']['1'] = "Éditer les participants du questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey']['statistics']['0'] = "Statistiques";
$GLOBALS['TL_LANG']['tl_survey']['statistics']['1'] = "Afficher les statistiques du questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey']['pintan']['0'] = "Codes TAN";
$GLOBALS['TL_LANG']['tl_survey']['pintan']['1'] = "Créer des codes TAN pour le questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey']['copy']['0'] = "Dupliquer le questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['copy']['1'] = "Dupliquer le questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey']['delete']['0'] = "Supprimer le questionnaire";
$GLOBALS['TL_LANG']['tl_survey']['delete']['1'] = "Supprimer le questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey']['head_legend'] = "Paramètres de l'en-tête";
$GLOBALS['TL_LANG']['tl_survey']['title_legend'] = "Titre et description";
$GLOBALS['TL_LANG']['tl_survey']['activation_legend'] = "Activation";
$GLOBALS['TL_LANG']['tl_survey']['access_legend'] = "Accès";
$GLOBALS['TL_LANG']['tl_survey']['texts_legend'] = "Déclarations (Statements)";
$GLOBALS['TL_LANG']['tl_survey']['misc_legend'] = "Paramètres généraux";
 
?>
