<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey_pin_tan.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['createtan'] = "Créer des codes TAN";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['exporttan'] = "Exporter les codes TAN";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tans'] = "Codes TAN";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['sort'] = "Tri";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['url'] = "Adresse internet";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['create'] = "Créer";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['export'] = "Exporter";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan_used'] = "Le code TAN est utilisé";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan_new'] = "Le code TAN n'est pas utilisé";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['nrOfTAN']['0'] = "Nombre de codes TAN";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['nrOfTAN']['1'] = "Saisir un chiffre pour le nombre de codes TAN que vous voulez créer.";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['surveyPage']['0'] = "Page de questionnaire";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['surveyPage']['1'] = "Choisir la page qui contient le questionnaire. Si une page est sélectionnée une URL vers le questionnaire contenant le code TAN sera crée pour l'export.";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan']['0'] = "TAN";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan']['1'] = "Numéro d'authentification de transaction (code TAN)";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tstamp']['0'] = "Créé";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tstamp']['1'] = "Créé";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['used']['0'] = "Code TAN utilisé";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['used']['1'] = "Le code TAN a déjà été utilisé par un participant";
 
?>
