<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey_page.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_page']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_survey_page']['title']['1'] = "Saisir le titre de la page.";
$GLOBALS['TL_LANG']['tl_survey_page']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_survey_page']['description']['1'] = "Saisir une description pour la page.";
$GLOBALS['TL_LANG']['tl_survey_page']['tstamp']['0'] = "Dernière modification";
$GLOBALS['TL_LANG']['tl_survey_page']['tstamp']['1'] = "Date et heure des dernières modifications.";
$GLOBALS['TL_LANG']['tl_survey_page']['introduction']['0'] = "Introduction";
$GLOBALS['TL_LANG']['tl_survey_page']['introduction']['1'] = "Saisir une introduction. L'introduction est affichée au début de la page.";
$GLOBALS['TL_LANG']['tl_survey_page']['page_template']['0'] = "Modèle de page";
$GLOBALS['TL_LANG']['tl_survey_page']['page_template']['1'] = "Choisir le modèle de page.";
$GLOBALS['TL_LANG']['tl_survey_page']['new']['0'] = "Nouvelle page";
$GLOBALS['TL_LANG']['tl_survey_page']['new']['1'] = "Créer une nouvelle page";
$GLOBALS['TL_LANG']['tl_survey_page']['show']['0'] = "Afficher les détails";
$GLOBALS['TL_LANG']['tl_survey_page']['show']['1'] = "Afficher les détails de la page ID %s";
$GLOBALS['TL_LANG']['tl_survey_page']['cut']['0'] = "Déplacer la page";
$GLOBALS['TL_LANG']['tl_survey_page']['cut']['1'] = "Déplacer la page ID %s";
$GLOBALS['TL_LANG']['tl_survey_page']['edit']['0'] = "Éditer la page";
$GLOBALS['TL_LANG']['tl_survey_page']['edit']['1'] = "Éditer la page  ID %s";
$GLOBALS['TL_LANG']['tl_survey_page']['copy']['0'] = "Dupliquer la page";
$GLOBALS['TL_LANG']['tl_survey_page']['copy']['1'] = "Dupliquer la page ID %s";
$GLOBALS['TL_LANG']['tl_survey_page']['delete']['0'] = "Supprimer la page";
$GLOBALS['TL_LANG']['tl_survey_page']['delete']['1'] = "Supprimer la page ID %s";
$GLOBALS['TL_LANG']['tl_survey_page']['page'] = "Page";
$GLOBALS['TL_LANG']['tl_survey_page']['title_legend'] = "Titre et description";
$GLOBALS['TL_LANG']['tl_survey_page']['intro_legend'] = "Introduction";
$GLOBALS['TL_LANG']['tl_survey_page']['template_legend'] = "Paramètres du modèle";
 
?>
