<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey_question.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_question']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_survey_question']['title']['1'] = "Saisir le titre de la question.";
$GLOBALS['TL_LANG']['tl_survey_question']['author']['0'] = "Auteur";
$GLOBALS['TL_LANG']['tl_survey_question']['author']['1'] = "Saisir le nom de l'auteur.";
$GLOBALS['TL_LANG']['tl_survey_question']['questiontype']['0'] = "Type de question";
$GLOBALS['TL_LANG']['tl_survey_question']['questiontype']['1'] = "Choisir un type de question.";
$GLOBALS['TL_LANG']['tl_survey_question']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_survey_question']['description']['1'] = "Saisir une description pour la question.";
$GLOBALS['TL_LANG']['tl_survey_question']['question']['0'] = "Texte de la question";
$GLOBALS['TL_LANG']['tl_survey_question']['question']['1'] = "Saisir le texte de la question.";
$GLOBALS['TL_LANG']['tl_survey_question']['language']['0'] = "Langue";
$GLOBALS['TL_LANG']['tl_survey_question']['language']['1'] = "Choisir une langue pour la question.";
$GLOBALS['TL_LANG']['tl_survey_question']['obligatory']['0'] = "Obligatoire";
$GLOBALS['TL_LANG']['tl_survey_question']['obligatory']['1'] = "Une question obligatoire nécessite une réponse.";
$GLOBALS['TL_LANG']['tl_survey_question']['help']['0'] = "Aide";
$GLOBALS['TL_LANG']['tl_survey_question']['help']['1'] = "Saisir une aide qui sera affichée après le titre de la question.";
$GLOBALS['TL_LANG']['tl_survey_question']['introduction']['0'] = "Introduction";
$GLOBALS['TL_LANG']['tl_survey_question']['introduction']['1'] = "Saisir une introduction qui sera affichée au début de la page.";
$GLOBALS['TL_LANG']['tl_survey_question']['lower_bound']['0'] = "Limite inférieure";
$GLOBALS['TL_LANG']['tl_survey_question']['lower_bound']['1'] = "Saisir  la limite inférieure de la fourchette.";
$GLOBALS['TL_LANG']['tl_survey_question']['upper_bound']['0'] = "Limite supérieure";
$GLOBALS['TL_LANG']['tl_survey_question']['upper_bound']['1'] = "Saisir  la limite supérieure de la fourchette.";
$GLOBALS['TL_LANG']['tl_survey_question']['choices']['0'] = "Choix";
$GLOBALS['TL_LANG']['tl_survey_question']['choices']['1'] = "Utiliser les boutons pour créer, copier, déplacer ou supprimer des colonnes. Si JavaScript est désactivé, sauvegarder avant de changer la structure des choix !";
$GLOBALS['TL_LANG']['tl_survey_question']['hidetitle']['0'] = "Masquer le titre de la question";
$GLOBALS['TL_LANG']['tl_survey_question']['hidetitle']['1'] = "Ne pas afficher le titre de la question pendant l'exécution du questionnaire.";
$GLOBALS['TL_LANG']['tl_survey_question']['addother']['0'] = "Ajouter un choix supplémentaire";
$GLOBALS['TL_LANG']['tl_survey_question']['addother']['1'] = "Ajouter un choix supplémentaire (autre) avec un champ texte.";
$GLOBALS['TL_LANG']['tl_survey_question']['addscale']['0'] = "Ajouter un jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_question']['addscale']['1'] = "Choisir un jeu d'étiquettes parmi la liste des jeux et l'ajouter à la question.";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_style']['0'] = "Présentation des réponses";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_style']['1'] = "Choisir une présentation pour les réponses.";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_style']['vertical'] = "Choix alignés verticalement";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_style']['horizontal'] = "Choix alignés horizontalement";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_style']['select'] = "Menu déroulant";
$GLOBALS['TL_LANG']['tl_survey_question']['othertitle']['0'] = "Autre titre";
$GLOBALS['TL_LANG']['tl_survey_question']['othertitle']['1'] = "Saisir un titre pour le choix supplémentaire. Le texte sera affiché devant le champ texte.";
$GLOBALS['TL_LANG']['tl_survey_question']['scale']['0'] = "Jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_question']['scale']['1'] = "Choisir un jeu d'étiquettes parmi la liste.";
$GLOBALS['TL_LANG']['tl_survey_question']['save_add_scale'] = "Ajouter un jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_subtype']['0'] = "Sous-type";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_subtype']['1'] = "Choisir un sous-type de question ouverte.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_textbefore']['0'] = "Libellé devant le champ";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_textbefore']['1'] = "Saisir un libellé qui sera affiché devant le champ texte.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_textafter']['0'] = "Libellé après le champ";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_textafter']['1'] = "Saisir un nom qui sera affiché après le champ texte.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_textinside']['0'] = "Valeur par défaut";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_textinside']['1'] = "Saisir une valeur par défaut pour le champ.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_rows']['0'] = "Lignes";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_rows']['1'] = "Saisir le nombre de ligne pour la zone de texte.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_cols']['0'] = "Colonnes";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_cols']['1'] = "Saisir un nombre de colonnes pour la zone de texte.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_width']['0'] = "Largeur";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_width']['1'] = "Saisir la largeur du champ texte en nombre de caractères.";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_maxlen']['0'] = "Longueur maximale";
$GLOBALS['TL_LANG']['tl_survey_question']['openended_maxlen']['1'] = "Saisir la longueur maximale du champ texte en nombre de caractère.";
$GLOBALS['TL_LANG']['tl_survey_question']['multiplechoice_subtype']['0'] = "Sous-type";
$GLOBALS['TL_LANG']['tl_survey_question']['multiplechoice_subtype']['1'] = "Choisir un sous-type de question à choix multiple.";
$GLOBALS['TL_LANG']['tl_survey_question']['matrix_subtype']['0'] = "Sous-type";
$GLOBALS['TL_LANG']['tl_survey_question']['matrix_subtype']['1'] = "Choisir un sous-type de question matricielle.";
$GLOBALS['TL_LANG']['tl_survey_question']['matrixrows']['0'] = "Lignes";
$GLOBALS['TL_LANG']['tl_survey_question']['matrixrows']['1'] = "Utiliser les boutons pour créer, copier, déplacer ou supprimer des colonnes. Si JavaScript est désactivé, sauvegarder avant de changer la structure des lignes !";
$GLOBALS['TL_LANG']['tl_survey_question']['matrixcolumns']['0'] = "Colonnes";
$GLOBALS['TL_LANG']['tl_survey_question']['matrixcolumns']['1'] = "Utiliser les boutons pour créer, copier, déplacer ou supprimer des colonnes. Si JavaScript est désactivé, sauvegarder avant de changer la structure des colonnes !";
$GLOBALS['TL_LANG']['tl_survey_question']['addneutralcolumn']['0'] = "Ajouter une colonne neutre";
$GLOBALS['TL_LANG']['tl_survey_question']['addneutralcolumn']['1'] = "Ajouter une colonne neutre comme dernière colonne (indéfini, ne sais pas, etc.) pour la question matricielle.";
$GLOBALS['TL_LANG']['tl_survey_question']['neutralcolumn']['0'] = "Colonne neutre";
$GLOBALS['TL_LANG']['tl_survey_question']['neutralcolumn']['1'] = "Saisir le texte de la colonne neutre.";
$GLOBALS['TL_LANG']['tl_survey_question']['addbipolar']['0'] = "Afficher les attributs bipolaires";
$GLOBALS['TL_LANG']['tl_survey_question']['addbipolar']['1'] = "Afficher des attributs bipolaires pour la question matricielle (ex. bon - mauvais, léger – lourd, etc.).";
$GLOBALS['TL_LANG']['tl_survey_question']['adjective1']['0'] = "Attribut de gauche";
$GLOBALS['TL_LANG']['tl_survey_question']['adjective1']['1'] = "Saisir le texte de l'attribut de gauche.";
$GLOBALS['TL_LANG']['tl_survey_question']['adjective2']['0'] = "Attribut de droite";
$GLOBALS['TL_LANG']['tl_survey_question']['adjective2']['1'] = "Saisir le texte de l'attribut de droite.";
$GLOBALS['TL_LANG']['tl_survey_question']['bipolarposition']['0'] = "Position des attributs";
$GLOBALS['TL_LANG']['tl_survey_question']['bipolarposition']['1'] = "Choisir la position des attributs bipolaires de la question matricielle.";
$GLOBALS['TL_LANG']['tl_survey_question']['bipolarposition']['top'] = "Au-dessus de la tête de colonne";
$GLOBALS['TL_LANG']['tl_survey_question']['bipolarposition']['aside'] = "Gauche et droite des colonnes";
$GLOBALS['TL_LANG']['tl_survey_question']['new']['0'] = "Nouvelle question";
$GLOBALS['TL_LANG']['tl_survey_question']['new']['1'] = "Créer une nouvelle question";
$GLOBALS['TL_LANG']['tl_survey_question']['show']['0'] = "Détails";
$GLOBALS['TL_LANG']['tl_survey_question']['show']['1'] = "Afficher les détails de la question ID %s";
$GLOBALS['TL_LANG']['tl_survey_question']['edit']['0'] = "Editer la question";
$GLOBALS['TL_LANG']['tl_survey_question']['edit']['1'] = "Editer la question ID %s";
$GLOBALS['TL_LANG']['tl_survey_question']['copy']['0'] = "Dupliquer la question";
$GLOBALS['TL_LANG']['tl_survey_question']['copy']['1'] = "Dupliquer la question ID %s";
$GLOBALS['TL_LANG']['tl_survey_question']['cut']['0'] = "Déplacer la question";
$GLOBALS['TL_LANG']['tl_survey_question']['cut']['1'] = "Déplacer la question ID %s";
$GLOBALS['TL_LANG']['tl_survey_question']['up']['0'] = "Déplacer vers le haut";
$GLOBALS['TL_LANG']['tl_survey_question']['up']['1'] = "Déplacer la question ID %s vers le haut";
$GLOBALS['TL_LANG']['tl_survey_question']['down']['0'] = "Déplacer vers le bas";
$GLOBALS['TL_LANG']['tl_survey_question']['down']['1'] = "Déplacer la question ID %s vers le bas";
$GLOBALS['TL_LANG']['tl_survey_question']['delete']['0'] = "Supprimer la question";
$GLOBALS['TL_LANG']['tl_survey_question']['delete']['1'] = "Supprimer la question ID %s";
$GLOBALS['TL_LANG']['tl_survey_question']['details']['0'] = "Statistiques détaillées";
$GLOBALS['TL_LANG']['tl_survey_question']['details']['1'] = "Afficher les statistiques détaillées de la question ID %s";
$GLOBALS['TL_LANG']['tl_survey_question']['openended'] = "Question ouverte";
$GLOBALS['TL_LANG']['tl_survey_question']['oe_singleline'] = "Une seule ligne";
$GLOBALS['TL_LANG']['tl_survey_question']['oe_multiline'] = "Multi-lignes";
$GLOBALS['TL_LANG']['tl_survey_question']['oe_integer'] = "Nombre entier";
$GLOBALS['TL_LANG']['tl_survey_question']['oe_float'] = "Nombre à virgule flottante";
$GLOBALS['TL_LANG']['tl_survey_question']['oe_date'] = "Date";
$GLOBALS['TL_LANG']['tl_survey_question']['oe_time'] = "Temps";
$GLOBALS['TL_LANG']['tl_survey_question']['multiplechoice'] = "Question à choix multiples";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_singleresponse'] = "Réponse unique";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_multipleresponse'] = "Réponse multiple";
$GLOBALS['TL_LANG']['tl_survey_question']['mc_dichotomous'] = "Dichotomique (Oui/Non)";
$GLOBALS['TL_LANG']['tl_survey_question']['matrix'] = "Question matricielle";
$GLOBALS['TL_LANG']['tl_survey_question']['matrix_singleresponse'] = "Une réponse par ligne (réponse unique)";
$GLOBALS['TL_LANG']['tl_survey_question']['matrix_multipleresponse'] = "Réponses multiples par ligne (réponse multiple)";
$GLOBALS['TL_LANG']['tl_survey_question']['constantsum'] = "Somme constante";
$GLOBALS['TL_LANG']['tl_survey_question']['sum']['0'] = "Somme";
$GLOBALS['TL_LANG']['tl_survey_question']['sum']['1'] = "Saisir une valeur pour la somme.";
$GLOBALS['TL_LANG']['tl_survey_question']['sum']['exact'] = "La somme des valeurs saisies doit être égale à la valeur de la somme.";
$GLOBALS['TL_LANG']['tl_survey_question']['sum']['max'] = "La somme des valeurs saisies ne doit être supérieure à la valeur de la somme.";
$GLOBALS['TL_LANG']['tl_survey_question']['sumoption']['0'] = "Calcul";
$GLOBALS['TL_LANG']['tl_survey_question']['sumoption']['1'] = "Sélectionner une option pour comparer les valeurs saisies avec la valeur de somme.";
$GLOBALS['TL_LANG']['tl_survey_question']['inputfirst']['0'] = "Afficher les champs de saisie";
$GLOBALS['TL_LANG']['tl_survey_question']['inputfirst']['1'] = "Afficher les champs du texte de la réponse (Par défaut après le texte de la réponse).";
$GLOBALS['TL_LANG']['tl_survey_question']['answered'] = "Répondus";
$GLOBALS['TL_LANG']['tl_survey_question']['skipped'] = "Passés";
$GLOBALS['TL_LANG']['tl_survey_question']['most_selected_value'] = "Valeur la plus sélectionnée";
$GLOBALS['TL_LANG']['tl_survey_question']['nr_of_selections'] = "Nombre de sélections";
$GLOBALS['TL_LANG']['tl_survey_question']['median'] = "Moyen";
$GLOBALS['TL_LANG']['tl_survey_question']['arithmeticmean'] = "Moyenne arithmétique";
$GLOBALS['TL_LANG']['tl_survey_question']['yes'] = "Oui";
$GLOBALS['TL_LANG']['tl_survey_question']['no'] = "Non";
$GLOBALS['TL_LANG']['tl_survey_question']['title_legend'] = "Titre et type de question";
$GLOBALS['TL_LANG']['tl_survey_question']['question_legend'] = "Texte de la question";
$GLOBALS['TL_LANG']['tl_survey_question']['obligatory_legend'] = "Saisie obligatoire";
$GLOBALS['TL_LANG']['tl_survey_question']['specific_legend'] = "Paramètres spécifiques";
$GLOBALS['TL_LANG']['tl_survey_question']['rows_legend'] = "Lignes de la matrice";
$GLOBALS['TL_LANG']['tl_survey_question']['columns_legend'] = "Colonnes de la matrice";
$GLOBALS['TL_LANG']['tl_survey_question']['bipolar_legend'] = "Attributs bipolaires";
$GLOBALS['TL_LANG']['tl_survey_question']['sum_legend'] = "Options de somme";
 
?>
