<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey_scale_folder.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['title']['1'] = "Saisir le nom du classeur.";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['description']['1'] = "Saisir la description du classeur";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['tstamp']['0'] = "Dernière modification";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['tstamp']['1'] = "Date et heure des dernières modifications.";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['new']['0'] = "Nouveau classeur";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['new']['1'] = "Créer un nouveau classeur";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['show']['0'] = "Détails du classeur";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['show']['1'] = "Montrer les détails du classeur ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['edit']['0'] = "Éditer le jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['edit']['1'] = "Éditer le jeu d'étiquettes du classeur ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['copy']['0'] = "Dupliquer le classeur";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['copy']['1'] = "Dupliquer le classeur ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['delete']['0'] = "Supprimer le classeur";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['delete']['1'] = "Supprimer le classeur ID %s";
 
?>
