<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey_participant.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_participant']['show']['0'] = "Détails des données des participants au questionnaire";
$GLOBALS['TL_LANG']['tl_survey_participant']['show']['1'] = "Afficher les détails des données des participants au questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey_participant']['delete']['0'] = "Supprimer les données des participants au questionnaire";
$GLOBALS['TL_LANG']['tl_survey_participant']['delete']['1'] = "Supprimer les données des participants au questionnaire ID %s";
$GLOBALS['TL_LANG']['tl_survey_participant']['tstamp']['0'] = "Date de modification";
$GLOBALS['TL_LANG']['tl_survey_participant']['tstamp']['1'] = "Date de la dernière modification par les participants";
$GLOBALS['TL_LANG']['tl_survey_participant']['lastpage']['0'] = "Dernière page";
$GLOBALS['TL_LANG']['tl_survey_participant']['lastpage']['1'] = "Numéro de la dernière page qu'un participant a visité";
$GLOBALS['TL_LANG']['tl_survey_participant']['exportraw']['0'] = "Export détaillé";
$GLOBALS['TL_LANG']['tl_survey_participant']['exportraw']['1'] = "Exportation détaillée avec toutes les réponses des participants.";
$GLOBALS['TL_LANG']['tl_survey_participant']['finished'] = "Terminé";
$GLOBALS['TL_LANG']['tl_survey_participant']['running'] = "Démarré";
 
?>
