<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/modules.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['surveys'] = "Umfragen";
$GLOBALS['TL_LANG']['MOD']['survey']['0'] = "Umfragen";
$GLOBALS['TL_LANG']['MOD']['survey']['1'] = "Mit diesem Modul können Sie Umfragen erstellen und bearbeiten.";
$GLOBALS['TL_LANG']['MOD']['scale']['0'] = "Skalen";
$GLOBALS['TL_LANG']['MOD']['scale']['1'] = "Mit diesem Modul können Sie ordinale Skalen für Umfragen erstellen und bearbeiten.";
 
?>
