<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_survey.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_survey']['title']['1'] = "Bitte geben Sie den Titel der Umfrage ein.";
$GLOBALS['TL_LANG']['tl_survey']['author']['0'] = "Autor";
$GLOBALS['TL_LANG']['tl_survey']['author']['1'] = "Bitte geben Sie den Namen des Autors ein.";
$GLOBALS['TL_LANG']['tl_survey']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_survey']['description']['1'] = "Bitte geben Sie eine Beschreibung für die Umfrage ein.";
$GLOBALS['TL_LANG']['tl_survey']['tstamp']['0'] = "Zuletzt geändert";
$GLOBALS['TL_LANG']['tl_survey']['tstamp']['1'] = "Datum und Uhrzeit der letzten Änderung der Umfrage.";
$GLOBALS['TL_LANG']['tl_survey']['language']['0'] = "Sprache";
$GLOBALS['TL_LANG']['tl_survey']['language']['1'] = "Bitte wählen Sie die Sprache der Umfrage.";
$GLOBALS['TL_LANG']['tl_survey']['introduction']['0'] = "Einleitender Text";
$GLOBALS['TL_LANG']['tl_survey']['introduction']['1'] = "Bitte geben Sie einen einleitenden Text für die Umfrage ein, der auf einer gesonderten Startseite erscheint.";
$GLOBALS['TL_LANG']['tl_survey']['finalsubmission']['0'] = "Abschließender Text";
$GLOBALS['TL_LANG']['tl_survey']['finalsubmission']['1'] = "Bitte geben Sie einen abschließenden Text ein, der nach dem Beenden der Umfrage erscheint.";
$GLOBALS['TL_LANG']['tl_survey']['online_start']['0'] = "Aktiviert ab";
$GLOBALS['TL_LANG']['tl_survey']['online_start']['1'] = "Wenn Sie hier ein Datum erfassen, wird die Umfrage erst ab diesem Tag aktiviert.";
$GLOBALS['TL_LANG']['tl_survey']['online_end']['0'] = "Aktiviert bis";
$GLOBALS['TL_LANG']['tl_survey']['online_end']['1'] = "Wenn Sie hier ein Datum erfassen, wird die Umfrage nur bis zu diesem Tag aktiviert.";
$GLOBALS['TL_LANG']['tl_survey']['limit_groups']['0'] = "Limitieren auf Mitgliedergruppen";
$GLOBALS['TL_LANG']['tl_survey']['limit_groups']['1'] = "Limitieren Sie den Zugriff auf ausgewählte Mitgliedergruppen.";
$GLOBALS['TL_LANG']['tl_survey']['allowed_groups']['0'] = "Mitgliedergruppen";
$GLOBALS['TL_LANG']['tl_survey']['allowed_groups']['1'] = "Wählen Sie die Mitgliedergruppen aus, welche die Umfrage durchführen dürfen.";
$GLOBALS['TL_LANG']['tl_survey']['access']['0'] = "Umfrageverfahren";
$GLOBALS['TL_LANG']['tl_survey']['access']['1'] = "Bitte wählen Sie das von Ihnen gewünschte Umfrageverfahren aus.";
$GLOBALS['TL_LANG']['tl_survey']['access']['explanation'] = "Bitte wählen Sie das von Ihnen gewünschte Umfrageverfahren aus.";
$GLOBALS['TL_LANG']['tl_survey']['access']['anon']['0'] = "Anonymisierte Umfrage";
$GLOBALS['TL_LANG']['tl_survey']['access']['anon']['1'] = "Umfrageteilnehmer benötigen keinen Zugangscode für die Umfrage. Eine Zuordnung der Umfrageteilnehmer zu den Umfrageergebnissen ist nicht möglich.";
$GLOBALS['TL_LANG']['tl_survey']['access']['anoncode']['0'] = "Anonymisierte Umfrage mit TAN";
$GLOBALS['TL_LANG']['tl_survey']['access']['anoncode']['1'] = "Umfrageteilnehmer können die Umfrage nur mit einem Zugangscode (Transaktiosnnummer, TAN) starten. Eine Umfrage kann nur genau ein Mal pro Teilnehmer durchgeführt werden. Eine Zuordnung der Umfrageteilnehmer zu den Umfrageergebnissen ist nicht möglich.";
$GLOBALS['TL_LANG']['tl_survey']['access']['nonanoncode']['0'] = "Personalisierte Umfrage";
$GLOBALS['TL_LANG']['tl_survey']['access']['nonanoncode']['1'] = "Umfrageteilnehmer können die Umfrage nur starten, wenn Sie angemeldete TYPOlight-Mitglieder sind. Eine Umfrage kann nur genau ein Mal pro Teilnehmer durchgeführt werden. Die Umfrageergebnisse können in der Auswertung den einzelnen Umfrageteilnehmern zugeordnet werden.";
$GLOBALS['TL_LANG']['tl_survey']['usecookie']['0'] = "Teilnehmer wiedererkennen";
$GLOBALS['TL_LANG']['tl_survey']['usecookie']['1'] = "Bitte wählen Sie, ob Teilnehmer mit Hilfe eines Cookies wiedererkannt werden sollen.";
$GLOBALS['TL_LANG']['tl_survey']['show_title']['0'] = "Umfragetitel anzeigen";
$GLOBALS['TL_LANG']['tl_survey']['show_title']['1'] = "Zeigt den Umfragetitel dauerhaft in einer Kopfzeile über der Umfrage an.";
$GLOBALS['TL_LANG']['tl_survey']['show_cancel']['0'] = "Diese Umfrage beenden";
$GLOBALS['TL_LANG']['tl_survey']['show_cancel']['1'] = "Zeigt während der Umfrage dauerhaft ein <strong>Diese Umfrage beenden</strong> Kommando in einer Kopfzeile über der Umfrage an.";
$GLOBALS['TL_LANG']['tl_survey']['allowback']['0'] = "Zurückgehen erlauben";
$GLOBALS['TL_LANG']['tl_survey']['allowback']['1'] = "Bitte wählen Sie, ob Teilnehmer auf eine vorherige Seite der Umfrage zurückgehen dürfen.";
$GLOBALS['TL_LANG']['tl_survey']['immediate_start']['0'] = "Umfrage sofort starten";
$GLOBALS['TL_LANG']['tl_survey']['immediate_start']['1'] = "Bitte wählen Sie, ob das Formular der Umfrage sofort angezeigt werden soll.";
$GLOBALS['TL_LANG']['tl_survey']['jumpto']['0'] = "Weiterleitung zu Seite";
$GLOBALS['TL_LANG']['tl_survey']['jumpto']['1'] = "Mit dieser Einstellung legen Sie fest, auf welche Seite ein Benutzer nach dem Beenden der Umfrage weitergeleitet wird.";
$GLOBALS['TL_LANG']['tl_survey']['new']['0'] = "Neue Umfrage";
$GLOBALS['TL_LANG']['tl_survey']['new']['1'] = "Eine neue Umfrage anlegen";
$GLOBALS['TL_LANG']['tl_survey']['show']['0'] = "Umfragedetails";
$GLOBALS['TL_LANG']['tl_survey']['show']['1'] = "Details der Umfrage ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_survey']['edit']['0'] = "Umfrage bearbeiten";
$GLOBALS['TL_LANG']['tl_survey']['edit']['1'] = "Umfrage ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_survey']['edit_']['0'] = "Umfrage kann nicht bearbeitet werden";
$GLOBALS['TL_LANG']['tl_survey']['edit_']['1'] = "Die Umfrage ID %s kann nicht bearbeitet werden, da bereits Teilnehmerdatensätze existieren.";
$GLOBALS['TL_LANG']['tl_survey']['participants']['0'] = "Umfrageteilnehmer";
$GLOBALS['TL_LANG']['tl_survey']['participants']['1'] = "Teilnehmer der Umfrage ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_survey']['statistics']['0'] = "Statistik";
$GLOBALS['TL_LANG']['tl_survey']['statistics']['1'] = "Statistik der Umfrage ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_survey']['pintan']['0'] = "TAN-Erzeugung";
$GLOBALS['TL_LANG']['tl_survey']['pintan']['1'] = "TAN-Erzeugung für die Umfrage ID %s öffnen";
$GLOBALS['TL_LANG']['tl_survey']['copy']['0'] = "Umfrage duplizieren";
$GLOBALS['TL_LANG']['tl_survey']['copy']['1'] = "Umfrage ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_survey']['delete']['0'] = "Umfrage löschen";
$GLOBALS['TL_LANG']['tl_survey']['delete']['1'] = "Umfrage ID %s löschen";
$GLOBALS['TL_LANG']['tl_survey']['head_legend'] = "Einstellungen für die Kopfzeile";
$GLOBALS['TL_LANG']['tl_survey']['title_legend'] = "Titel und Beschreibung";
$GLOBALS['TL_LANG']['tl_survey']['activation_legend'] = "Aktivierung";
$GLOBALS['TL_LANG']['tl_survey']['access_legend'] = "Zugriff";
$GLOBALS['TL_LANG']['tl_survey']['texts_legend'] = "Einleitende und abschließende Bemerkung";
$GLOBALS['TL_LANG']['tl_survey']['misc_legend'] = "Allgemeine Einstellungen";
 
?>
