<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_content.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['survey']['0'] = "Umfrage";
$GLOBALS['TL_LANG']['tl_content']['survey']['1'] = "Bitte wählen Sie eine Umfrage.";
$GLOBALS['TL_LANG']['tl_content']['enter_tan_to_start_desc'] = "Diese Umfrage kann nur mit einem TAN-Code gestartet werden, den Sie im Vorfeld erhalten haben.";
$GLOBALS['TL_LANG']['tl_content']['enter_tan_to_start'] = "TAN-Code";
$GLOBALS['TL_LANG']['tl_content']['survey_legend'] = "Umfrage-Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['surveyTpl']['0'] = "Umfragetemplate";
$GLOBALS['TL_LANG']['tl_content']['surveyTpl']['1'] = "Hier können Sie das Umfragetemplate auswählen.";

?>
