<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_survey_scale_folder.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['title']['1'] = "Bitte geben Sie den Titel des Ordners ein.";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['description']['1'] = "Bitte geben Sie eine Beschreibung des Ordners ein.";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['tstamp']['0'] = "Zuletzt geändert";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['tstamp']['1'] = "Datum und Uhrzeit der letzten Änderung des Ordners.";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['new']['0'] = "Neuer Ordner";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['new']['1'] = "Einen neuen Ordner anlegen";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['show']['0'] = "Ordnerdetails";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['show']['1'] = "Details des Ordners ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['edit']['0'] = "Skalen bearbeiten";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['edit']['1'] = "Skalen im Ordner ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['copy']['0'] = "Ordner duplizieren";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['copy']['1'] = "Ordner ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['delete']['0'] = "Ordner löschen";
$GLOBALS['TL_LANG']['tl_survey_scale_folder']['delete']['1'] = "Ordner ID %s löschen";
 
?>
