<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_survey_page.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_page']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_survey_page']['title']['1'] = "Bitte geben Sie den Titel der Seite ein.";
$GLOBALS['TL_LANG']['tl_survey_page']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_survey_page']['description']['1'] = "Bitte geben Sie eine Beschreibung der Seite ein.";
$GLOBALS['TL_LANG']['tl_survey_page']['tstamp']['0'] = "Zuletzt geändert";
$GLOBALS['TL_LANG']['tl_survey_page']['tstamp']['1'] = "Datum und Uhrzeit der letzten Änderung der Seite.";
$GLOBALS['TL_LANG']['tl_survey_page']['introduction']['0'] = "Einleitender Text";
$GLOBALS['TL_LANG']['tl_survey_page']['introduction']['1'] = "Bitte geben Sie einen einleitenden Text für die Seite ein. Der Text erscheint am Anfang der Seite vor der ersten Frage.";
$GLOBALS['TL_LANG']['tl_survey_page']['page_template']['0'] = "Seitentemplate";
$GLOBALS['TL_LANG']['tl_survey_page']['page_template']['1'] = "Hier können Sie ein Seitentemplate auswählen.";
$GLOBALS['TL_LANG']['tl_survey_page']['new']['0'] = "Neue Seite";
$GLOBALS['TL_LANG']['tl_survey_page']['new']['1'] = "Eine neue Seite anlegen";
$GLOBALS['TL_LANG']['tl_survey_page']['show']['0'] = "Seitendetails";
$GLOBALS['TL_LANG']['tl_survey_page']['show']['1'] = "Details der Seite ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_survey_page']['cut']['0'] = "Seite verschieben";
$GLOBALS['TL_LANG']['tl_survey_page']['cut']['1'] = "Seite ID %s verschieben";
$GLOBALS['TL_LANG']['tl_survey_page']['edit']['0'] = "Seite bearbeiten";
$GLOBALS['TL_LANG']['tl_survey_page']['edit']['1'] = "Seite ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_survey_page']['copy']['0'] = "Seite duplizieren";
$GLOBALS['TL_LANG']['tl_survey_page']['copy']['1'] = "Seite ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_survey_page']['delete']['0'] = "Seite löschen";
$GLOBALS['TL_LANG']['tl_survey_page']['delete']['1'] = "Seite ID %s löschen";
$GLOBALS['TL_LANG']['tl_survey_page']['page'] = "Seite";
$GLOBALS['TL_LANG']['tl_survey_page']['title_legend'] = "Titel und Beschreibung";
$GLOBALS['TL_LANG']['tl_survey_page']['intro_legend'] = "Einleitender Text";
$GLOBALS['TL_LANG']['tl_survey_page']['template_legend'] = "Template-Einstellungen";
 
?>
