<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_survey_scale.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_scale']['new']['0'] = "Neue Skala";
$GLOBALS['TL_LANG']['tl_survey_scale']['new']['1'] = "Eine neue Skala anlegen";
$GLOBALS['TL_LANG']['tl_survey_scale']['show']['0'] = "Skalendetails";
$GLOBALS['TL_LANG']['tl_survey_scale']['show']['1'] = "Details der Skala ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_survey_scale']['edit']['0'] = "Skala bearbeiten";
$GLOBALS['TL_LANG']['tl_survey_scale']['edit']['1'] = "Skala ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_survey_scale']['cut']['0'] = "Skala verschieben";
$GLOBALS['TL_LANG']['tl_survey_scale']['cut']['1'] = "Skala ID %s verschieben";
$GLOBALS['TL_LANG']['tl_survey_scale']['copy']['0'] = "Skala duplizieren";
$GLOBALS['TL_LANG']['tl_survey_scale']['copy']['1'] = "Skala ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_survey_scale']['delete']['0'] = "Skala löschen";
$GLOBALS['TL_LANG']['tl_survey_scale']['delete']['1'] = "Skala ID %s löschen";
$GLOBALS['TL_LANG']['tl_survey_scale']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_survey_scale']['title']['1'] = "Bitte geben Sie den Titel der Skala ein.";
$GLOBALS['TL_LANG']['tl_survey_scale']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_survey_scale']['description']['1'] = "Bitte geben Sie eine Beschreibung für die Skala ein.";
$GLOBALS['TL_LANG']['tl_survey_scale']['tstamp']['0'] = "Zuletzt geändert";
$GLOBALS['TL_LANG']['tl_survey_scale']['tstamp']['1'] = "Datum und Uhrzeit der letzten Änderung der Skala.";
$GLOBALS['TL_LANG']['tl_survey_scale']['language']['0'] = "Sprache";
$GLOBALS['TL_LANG']['tl_survey_scale']['language']['1'] = "Bitte wählen Sie die Sprache der Skala.";
$GLOBALS['TL_LANG']['tl_survey_scale']['scale']['0'] = "Antworten";
$GLOBALS['TL_LANG']['tl_survey_scale']['scale']['1'] = "Benutzen Sie die Schaltflächen, um Antworten zu kopieren, zu verschieben oder zu löschen. Wenn Sie ohne JavaScript-Unterstützung arbeiten, sollten Sie Ihre Eingaben speichern bevor Sie die Struktur der Antworten verändern!";
$GLOBALS['TL_LANG']['tl_survey_scale']['title_legend'] = "Titel und Beschreibung";
$GLOBALS['TL_LANG']['tl_survey_scale']['scale_legend'] = "Skalen (Antworten)";
 
?>
