<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_survey_pin_tan.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['createtan'] = "TAN-Codes erzeugen";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['exporttan'] = "TAN-Codes exportieren";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tans'] = "TAN-Codes";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['sort'] = "Sortierung";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['url'] = "URL zur Umfrage";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['create'] = "Erzeugen";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['export'] = "Exportieren";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan_used'] = "Die TAN wurde bereits verwendet";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan_new'] = "Die TAN ist noch nicht verwendet worden";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['nrOfTAN']['0'] = "Anzahl der TAN-Codes";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['nrOfTAN']['1'] = "Bitte geben Sie die Anzahl der TAN-Codes ein, die Sie erzeugen möchten.";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['surveyPage']['0'] = "Seite der Umfrage";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['surveyPage']['1'] = "Bitte wählen Sie die Seite aus, auf der Sie die Umfrage durchführen wollen. Bei einer ausgewählten Seite wird eine Start-URL mit dem zugehörigen TAN-Code generiert.";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan']['0'] = "TAN";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tan']['1'] = "Transaktionnummer (TAN)";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tstamp']['0'] = "Erstellungsdatum";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['tstamp']['1'] = "Erstellungsdatum";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['used']['0'] = "TAN wurde benutzt";
$GLOBALS['TL_LANG']['tl_survey_pin_tan']['used']['1'] = "Die TAN wurde bereits von einem Teilnehmer benutzt";
 
?>
