<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/de/tl_survey_participant.php 
 * 
 * TYPOlight extension: survey_ce 1.0.2 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_participant']['show']['0'] = "Teilnehmerdatendetails";
$GLOBALS['TL_LANG']['tl_survey_participant']['show']['1'] = "Details des Teilnehmers ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_survey_participant']['delete']['0'] = "Teilnehmerdaten löschen";
$GLOBALS['TL_LANG']['tl_survey_participant']['delete']['1'] = "Teilnehmerdaten ID %s löschen";
$GLOBALS['TL_LANG']['tl_survey_participant']['tstamp']['0'] = "Änderungsdatum";
$GLOBALS['TL_LANG']['tl_survey_participant']['tstamp']['1'] = "Datum der letzten Änderung des Teilnehmers";
$GLOBALS['TL_LANG']['tl_survey_participant']['lastpage']['0'] = "Letzte Seite";
$GLOBALS['TL_LANG']['tl_survey_participant']['lastpage']['1'] = "Letzte Seite, die der Teilnehmer angesehen hat";
$GLOBALS['TL_LANG']['tl_survey_participant']['finished'] = "beendet";
$GLOBALS['TL_LANG']['tl_survey_participant']['running'] = "begonnen";
$GLOBALS['TL_LANG']['tl_survey_participant']['exportraw']['0'] = "Detaillierter Export";
$GLOBALS['TL_LANG']['tl_survey_participant']['exportraw']['1'] = "Export mit allen Teilnehmer-Antworten, filter- und sortierbar";

?>
