<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/default.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['survey']['0'] = "Questionnaire";
$GLOBALS['TL_LANG']['CTE']['survey']['1'] = "Inclure un questionnaire.";
$GLOBALS['TL_LANG']['MSC']['deleteAll'] = "Supprimer toutes les données des participants";
$GLOBALS['TL_LANG']['MSC']['survey_next'] = "Suivant";
$GLOBALS['TL_LANG']['MSC']['survey_prev'] = "Précédent";
$GLOBALS['TL_LANG']['MSC']['survey_start'] = "Démarrer le questionnaire";
$GLOBALS['TL_LANG']['MSC']['survey_finish'] = "Finir le questionnaire";
$GLOBALS['TL_LANG']['MSC']['survey_finalsubmission'] = "Merci pour votre participation à ce questionnaire.";
$GLOBALS['TL_LANG']['MSC']['cancel_survey'] = "Quitter ce questionnaire";
$GLOBALS['TL_LANG']['ERR']['survey_already_finished'] = "Vous avez déjà fini le questionnaire.";
$GLOBALS['TL_LANG']['ERR']['survey_please_enter_tan'] = "Entrer un code TAN pour démarrer ce questionnaire.";
$GLOBALS['TL_LANG']['ERR']['survey_wrong_tan'] = "Code TAN invalide. Saisir un code TAN valide.";
$GLOBALS['TL_LANG']['ERR']['survey_no_member'] = "Vous devez vous connecter pour participer à ce questionnaire.";
$GLOBALS['TL_LANG']['ERR']['survey_no_allowed_member'] = "Vous n'avez pas la permission de participer à ce questionnaire.";
$GLOBALS['TL_LANG']['ERR']['sumnotexact'] = "La somme des valeurs entrées à la question \"%s\" est différente de %s.";
$GLOBALS['TL_LANG']['ERR']['sumnotmax'] = "La somme des valeurs entrées à la question  \"%s\" est plus grande que %s.";
$GLOBALS['TL_LANG']['ERR']['selectoption'] = "Choisir une option";
$GLOBALS['TL_LANG']['ERR']['mandatory_constantsum'] = "Remplir complètement la question \"%s\".";
$GLOBALS['TL_LANG']['ERR']['mandatory_matrix'] = "Sélectionner au moins une option dans chaque ligne de la question \"%s\".";
$GLOBALS['TL_LANG']['ERR']['mandatory_mc_sr'] = "Sélectionner exactement une réponse à la question \"%s\".";
$GLOBALS['TL_LANG']['ERR']['mandatory_mc_mr'] = "Sélectionner au moins une réponse à la question \"%s\".";
$GLOBALS['TL_LANG']['ERR']['missing_other_value'] = "Vous avez coché réponse additionnelle mais vous n'avez pas saisi un texte.";
$GLOBALS['TL_LANG']['ERR']['lower_bound'] = "La valeur (%s) pour \"%s\" est plus petite que celle autorisée (%s).";
$GLOBALS['TL_LANG']['ERR']['upper_bound'] = "La valeur (%s) pour \"%s\" est plus grande que celle autorisée (%s).";
 
?>
