<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_content.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['survey']['0'] = "Questionnaire";
$GLOBALS['TL_LANG']['tl_content']['survey']['1'] = "Choisir un questionnaire.";
$GLOBALS['TL_LANG']['tl_content']['enter_tan_to_start_desc'] = "Le questionnaire est accessible seulement avec un code TAN que vous avez déjà du recevoir.";
$GLOBALS['TL_LANG']['tl_content']['enter_tan_to_start'] = "Code TAN";
$GLOBALS['TL_LANG']['tl_content']['survey_legend'] = "Paramètre du questionnaire";
$GLOBALS['TL_LANG']['tl_content']['surveyTpl']['0'] = "Modèle du questionnaire";
$GLOBALS['TL_LANG']['tl_content']['surveyTpl']['1'] = "Sélectionnez un modèle";
 
?>
