<?php
/**
 * TL_ROOT/system/modules/survey_ce/languages/fr/tl_survey_scale.php 
 * 
 * Contao extension: survey_ce 1.1.0 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_survey_scale']['new']['0'] = "Nouveau jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['new']['1'] = "Créer un nouveau jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['show']['0'] = "Détails du jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['show']['1'] = "Afficher les détails pour le jeu d'étiquettes ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale']['edit']['0'] = "Éditer le jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['edit']['1'] = "Éditer le jeu d'étiquettes ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale']['cut']['0'] = "Déplacer le jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['cut']['1'] = "Déplacer le jeu d'étiquettes ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale']['copy']['0'] = "Dupliquer le jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['copy']['1'] = "Dupliquer le jeu d'étiquettes ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale']['delete']['0'] = "Supprimer le jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['delete']['1'] = "Supprimer le jeu d'étiquettes ID %s";
$GLOBALS['TL_LANG']['tl_survey_scale']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_survey_scale']['title']['1'] = "Saisir le titre du jeu d'étiquettes";
$GLOBALS['TL_LANG']['tl_survey_scale']['description']['0'] = "Description";
$GLOBALS['TL_LANG']['tl_survey_scale']['description']['1'] = "Saisir une description pour le jeu d'étiquettes.";
$GLOBALS['TL_LANG']['tl_survey_scale']['tstamp']['0'] = "Dernière modification";
$GLOBALS['TL_LANG']['tl_survey_scale']['tstamp']['1'] = "Date et heure des dernières modifications.";
$GLOBALS['TL_LANG']['tl_survey_scale']['language']['0'] = "Langue";
$GLOBALS['TL_LANG']['tl_survey_scale']['language']['1'] = "Saisir une langue pour le jeu d'étiquettes.";
$GLOBALS['TL_LANG']['tl_survey_scale']['scale']['0'] = "Réponses";
$GLOBALS['TL_LANG']['tl_survey_scale']['scale']['1'] = "Utiliser les boutons pour créer, copier, déplacer ou supprimer des colonnes. Si JavaScript est désactivé, sauvegarder avant de changer la structure des réponses !";
$GLOBALS['TL_LANG']['tl_survey_scale']['title_legend'] = "Titre et description";
$GLOBALS['TL_LANG']['tl_survey_scale']['scale_legend'] = "Jeu d'étiquettes (réponses)";
 
?>
